### ISSUE TITLE
Nested transformation in vehicle.yaml

### ISSUE THREAD

**Issue by miquelmassot** [ocean-perception/oplab_pipeline#71]
Desirable to have the ability to write nested transformations:

```
origin:
  stereo_camera:
    left:
    right:
    laser:
```
